version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'

  api:
    image: {{crate_name}}:latest
    restart: always
    ports:
      - 8001:8001
    expose:
      - 8001
    links:
      - db
    environment:
      - PROFILE=docker-compose
